export interface Job {
    id: string;
    title: string;
    company: string;
    location: string;
    mode: "Remote" | "Hybrid" | "Onsite";
    experience: "Fresher" | "0-1 Years" | "1-3 Years" | "3-5 Years";
    skills: string[];
    source: "LinkedIn" | "Naukri" | "Indeed" | "Company Career Page" | "Internshala";
    postedDaysAgo: number;
    salaryRange: string;
    applyUrl: string;
    description: string;
}

export const jobs: Job[] = [
    // 1-10
    {
        id: "job-1",
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms", "AWS"],
        source: "Company Career Page",
        postedDaysAgo: 1,
        salaryRange: "₹45k–₹80k/month",
        applyUrl: "https://amazon.jobs/en/",
        description: "Join Amazon as a Software Development Engineer Intern. You will work on real-world problems, scalable systems, and cutting-edge technologies. Ideal for final year students with strong CS fundamentals."
    },
    {
        id: "job-2",
        title: "Frontend Developer (React)",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["React", "TypeScript", "Redux", "Tailwind CSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "#",
        description: "Swiggy is looking for a passionate Frontend Developer to build seamless user experiences. You will work with React, TypeScript, and modern styling frameworks to deliver high-performance web applications."
    },
    {
        id: "job-3",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "3.5–5 LPA",
        applyUrl: "#",
        description: "TCS is hiring fresh graduates for the position of Graduate Engineer Trainee. Excellent opportunity to start your career with a global IT leader. Training will be provided in various domains."
    },
    {
        id: "job-4",
        title: "Backend Engineer",
        company: "Razorpay",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Node.js", "Go", "PostgreSQL", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15–22 LPA",
        applyUrl: "#",
        description: "Razorpay is seeking a Backend Engineer to build robust payment infrastructure. You should have experience with distributed systems and high-scale APIs."
    },
    {
        id: "job-5",
        title: "QA Intern",
        company: "Zoho",
        location: "Chennai, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java", "Bug Tracking"],
        source: "Company Career Page",
        postedDaysAgo: 5,
        salaryRange: "₹15k–₹25k/month",
        applyUrl: "#",
        description: "Zoho Corp is looking for QA Interns. You will learn to test scalable SaaS applications and ensure high-quality software delivery. Good analytical skills required."
    },
    {
        id: "job-6",
        title: "Data Analyst",
        company: "PhonePe",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Python", "SQL", "Tableau", "Excel"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "#",
        description: "Analyze transaction data and provide insights to drive business decisions. Proficiency in SQL and data visualization tools is mandatory for this role at PhonePe."
    },
    {
        id: "job-7",
        title: "Java Developer",
        company: "Infosys",
        location: "Hyderabad, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Java", "Spring Boot", "Microservices", "Oracle"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5–9 LPA",
        applyUrl: "#",
        description: "Infosys is hiring Java Developers with hands-on experience in Spring Boot and Microservices. Join us to work on enterprise-grade applications for global clients."
    },
    {
        id: "job-8",
        title: "Product Designer",
        company: "CRED",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["Figma", "UI/UX", "Prototyping", "Visual Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–35 LPA",
        applyUrl: "#",
        description: "Design beautiful and intuitive financial products at CRED. We value attention to detail, strong visual design skills, and a user-centric approach."
    },
    {
        id: "job-9",
        title: "DevOps Engineer",
        company: "Freshworks",
        location: "Chennai, India",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–16 LPA",
        applyUrl: "#",
        description: "Manage cloud infrastructure and deployment pipelines. Experience with AWS and containerization technologies is essential for this role."
    },
    {
        id: "job-10",
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Gurgaon, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Java", "Database", "Analytical Skills"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4.5–6.5 LPA",
        applyUrl: "#",
        description: "Kickstart your career at Accenture. We are looking for entry-level software engineers to work across various technology stacks and industry verticals."
    },
    // 11-20
    {
        id: "job-11",
        title: "Frontend Intern",
        company: "Juspay",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["HTML", "CSS", "JavaScript", "React"],
        source: "Company Career Page",
        postedDaysAgo: 2,
        salaryRange: "₹20k–₹30k/month",
        applyUrl: "#",
        description: "Join Juspay's engineering team as a Frontend Intern. Work on payment UIs used by millions. PureScript/Haskell knowledge is a plus, but not mandatory."
    },
    {
        id: "job-12",
        title: "Python Developer",
        company: "Wipro",
        location: "Pune, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Python", "Django", "Flask", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4–7 LPA",
        applyUrl: "#",
        description: "Wipro is looking for Python developers to work on automation and backend services. Good understanding of data structures and algorithms is required."
    },
    {
        id: "job-13",
        title: "Full Stack Developer",
        company: "Flipkart",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["React", "Node.js", "System Design", "Scalability"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        applyUrl: "#",
        description: "Build scalable e-commerce solutions at Flipkart. You will own end-to-end development of features and work on high-traffic systems."
    },
    {
        id: "job-14",
        title: "Systems Engineer",
        company: "IBM",
        location: "Hyderabad, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Linux", "Networking", "Shell Scripting", "Python"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "4–6 LPA",
        applyUrl: "#",
        description: "IBM India is hiring Systems Engineers. You will support enterprise infrastructure and work with cutting-edge cloud technologies."
    },
    {
        id: "job-15",
        title: "Android Developer",
        company: "Paytm",
        location: "Noida, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Kotlin", "Android SDK", "Java", "MVVM"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "10–15 LPA",
        applyUrl: "#",
        description: "Develop the next generation of fintech apps at Paytm. Strong knowledge of Kotlin and Android architecture components is required."
    },
    {
        id: "job-16",
        title: "Cloud Support Associate",
        company: "Amazon Web Services",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Cloud Computing", "Networking", "OS", "Customer Handling"],
        source: "Company Career Page",
        postedDaysAgo: 0,
        salaryRange: "12–16 LPA",
        applyUrl: "#",
        description: "Start your cloud career with AWS. We are hiring Cloud Support Associates to help customers solve complex technical issues."
    },
    {
        id: "job-17",
        title: "Software Engineer",
        company: "Microsoft",
        location: "Hyderabad, India",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C#", ".NET", "Azure", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "14–20 LPA",
        applyUrl: "#",
        description: "Microsoft is hiring fresh graduates for software engineering roles. Work on products used by billions of people worldwide."
    },
    {
        id: "job-18",
        title: "Business Analyst",
        company: "Deloitte",
        location: "Mumbai, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Analysis", "Excel", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "7–11 LPA",
        applyUrl: "#",
        description: "Join Deloitte's consulting practice. You will analyze business processes and recommend technology solutions to clients."
    },
    {
        id: "job-19",
        title: "React Native Developer",
        company: "Groww",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["React Native", "JavaScript", "Mobile Dev", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "15–20 LPA",
        applyUrl: "#",
        description: "Build high-performance investment apps using React Native. Experience with native modules and performance optimization is a plus."
    },
    {
        id: "job-20",
        title: "Database Administrator",
        company: "Oracle",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Oracle DB", "SQL", "Performance Tuning", "Backup"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "12–18 LPA",
        applyUrl: "#",
        description: "Oracle is seeking experienced DBAs to manage mission-critical databases. Expertise in Oracle RAC and Data Guard is preferred."
    },
    // 21-30
    {
        id: "job-21",
        title: "Machine Learning Engineer",
        company: "Fractal Analytics",
        location: "Mumbai, India",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["Python", "TensorFlow", "PyTorch", "NLP"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–15 LPA",
        applyUrl: "#",
        description: "Work on advanced AI/ML solutions for Fortune 500 clients. Strong mathematical background and coding skills required."
    },
    {
        id: "job-22",
        title: "Software Engineer Intern",
        company: "Adobe",
        location: "Noida, India",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "JavaScript", "Algorithms", "OS"],
        source: "Company Career Page",
        postedDaysAgo: 1,
        salaryRange: "₹80k–₹1L/month",
        applyUrl: "#",
        description: "Adobe offers internships for students to work on Creative Cloud and Experience Cloud products. Great opportunity to learn from the best."
    },
    {
        id: "job-23",
        title: "Associate Consultant",
        company: "Capgemini",
        location: "Pune, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Testing", "SDLC", "Communication"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–5.5 LPA",
        applyUrl: "#",
        description: "Capgemini is hiring freshers for consulting roles. Training provided in Java, Testing, or Cloud technologies based on business needs."
    },
    {
        id: "job-24",
        title: "iOS Developer",
        company: "Zomato",
        location: "Gurgaon, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Swift", "iOS SDK", "Xcode", "UIKit"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–25 LPA",
        applyUrl: "#",
        description: "Build the Zomato iOS app. We are looking for developers who care about pixel-perfect UI and smooth animations."
    },
    {
        id: "job-25",
        title: "Technical Support Engineer",
        company: "Dell Technologies",
        location: "Bangalore, India",
        mode: "Remote",
        experience: "0-1 Years",
        skills: ["Hardware", "Networking", "Windows/Linux", "Troubleshooting"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "5–7 LPA",
        applyUrl: "#",
        description: "Provide technical support for enterprise servers and storage solutions. Strong problem-solving skills and technical knowledge required."
    },
    {
        id: "job-26",
        title: "Golang Developer",
        company: "Gojek",
        location: "Bangalore, India",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["Go", "Microservices", "gRPC", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "30–50 LPA",
        applyUrl: "#",
        description: "Join Gojek's platform team. Build high-throughput services using Go and distributed systems technologies."
    },
    {
        id: "job-27",
        title: "Cyber Security Analyst",
        company: "Paladion",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Network Security", "SIEM", "VAPT", "Ethical Hacking"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Monitor and respond to security threats. Experience with SIEM tools and vulnerability assessment is key."
    },
    {
        id: "job-28",
        title: "UI/UX Designer",
        company: "Myntra",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Figma", "User Research", "Wireframing", "Interaction Design"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "#",
        description: "Create fashion-forward digital experiences at Myntra. We need designers who understand e-commerce user journeys."
    },
    {
        id: "job-29",
        title: "SAP ABAP Consultant",
        company: "SAP Labs",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["ABAP", "SAP HANA", "OData", "Fiori"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        applyUrl: "#",
        description: "Develop and extend SAP solutions. Deep knowledge of ABAP objects and HANA database is required."
    },
    {
        id: "job-30",
        title: "Marketing Analyst",
        company: "Ola",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Excel", "Google Analytics", "SQL", "Marketing"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–9 LPA",
        applyUrl: "#",
        description: "Analyze marketing campaigns and user acquisition data. Help Ola grow efficiently through data-driven insights."
    },
    // 31-40
    {
        id: "job-31",
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["Solidity", "Smart Contracts", "Ethereum", "Web3.js"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "20–40 LPA",
        applyUrl: "#",
        description: "Build the future of Web3 at Polygon. Experience with Solidity and EVM-compatible chains is a must."
    },
    {
        id: "job-32",
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Python", "Linux", "Azure", "Automation"],
        source: "Company Career Page",
        postedDaysAgo: 5,
        salaryRange: "25–45 LPA",
        applyUrl: "#",
        description: "Keep LinkedIn running smoothly. SREs at LinkedIn automate operations and improve system reliability."
    },
    {
        id: "job-33",
        title: "Flutter Developer",
        company: "Dream11",
        location: "Mumbai, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Flutter", "Dart", "Mobile Dev", "Firebase"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "#",
        description: "Build cross-platform apps for sports fans. We use Flutter to deliver a consistent experience on iOS and Android."
    },
    {
        id: "job-34",
        title: "Technical Writer",
        company: "Salesforce",
        location: "Hyderabad, India",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["Technical Writing", "Documentation", "API Docs", "English"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "#",
        description: "Create clear and concise documentation for developers. Experience with markdown and API documentation tools needed."
    },
    {
        id: "job-35",
        title: "Game Developer",
        company: "Zynga",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Unity", "C#", "Game Design", "3D Math"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–12 LPA",
        applyUrl: "#",
        description: "Create fun and engaging mobile games. Unity proficiency and C# scripting skills are essential."
    },
    {
        id: "job-36",
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["CCNA", "Routing", "Switching", "Python"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "7–12 LPA",
        applyUrl: "#",
        description: "Work on the backbone of the internet. Cisco needs engineers with strong networking fundamentals and automation skills."
    },
    {
        id: "job-37",
        title: "HR Intern",
        company: "KPMG",
        location: "Gurgaon, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Communication", "HR Operations", "Excel", "Recruitment"],
        source: "Internshala",
        postedDaysAgo: 1,
        salaryRange: "₹15k/month",
        applyUrl: "#",
        description: "Support the HR team in recruitment and onboarding processes. Good communication skills are vital."
    },
    {
        id: "job-38",
        title: "Salesforce Developer",
        company: "Deloitte",
        location: "Hyderabad, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Apex", "Visualforce", "LWC", "Salesforce Cloud"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Customize Salesforce solutions for clients. Certification in Salesforce development is a plus."
    },
    {
        id: "job-39",
        title: "Ruby on Rails Developer",
        company: "Freshworks",
        location: "Chennai, India",
        mode: "Remote",
        experience: "3-5 Years",
        skills: ["Ruby", "Rails", "PostgreSQL", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–28 LPA",
        applyUrl: "#",
        description: "Build SaaS products using Ruby on Rails. We value clean code and test-driven development."
    },
    {
        id: "job-40",
        title: "Analyst",
        company: "Goldman Sachs",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Financial Analysis", "Excel", "SQL", "VBA"],
        source: "Company Career Page",
        postedDaysAgo: 0,
        salaryRange: "15–20 LPA",
        applyUrl: "#",
        description: "Join the operations or finance division. Strong analytical and quantitative skills are required."
    },
    // 41-50
    {
        id: "job-41",
        title: "Big Data Engineer",
        company: "Mu Sigma",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Hadoop", "Spark", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "5–7 LPA",
        applyUrl: "#",
        description: "Work with massive datasets to derive business value. Training provided in big data technologies."
    },
    {
        id: "job-42",
        title: "Angular Developer",
        company: "Mindtree",
        location: "Pune, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Angular", "TypeScript", "RxJS", "HTML/CSS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Develop enterprise web applications using Angular. Knowledge of state management and reactive programming is needed."
    },
    {
        id: "job-43",
        title: "Embedded Systems Engineer",
        company: "Bosch",
        location: "Bangalore, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["C", "C++", "Microcontrollers", "RTOS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–12 LPA",
        applyUrl: "#",
        description: "Develop software for automotive and industrial applications. Experience with embedded C and microcontrollers is required."
    },
    {
        id: "job-44",
        title: "Operations Executive",
        company: "Uber",
        location: "Hyderabad, India",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Operations", "Excel", "Communication", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "5–8 LPA",
        applyUrl: "#",
        description: "Manage city operations and driver partner relationships. Requires hustle and data-driven decision making."
    },
    {
        id: "job-45",
        title: "Graphic Designer",
        company: "Ogilvy",
        location: "Mumbai, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Photoshop", "Illustrator", "InDesign", "Creativity"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "4–7 LPA",
        applyUrl: "#",
        description: "Design compelling visuals for advertising campaigns. Strong portfolio is mandatory."
    },
    {
        id: "job-46",
        title: "React Developer",
        company: "Meesho",
        location: "Bangalore, India",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["React", "JavaScript", "Redux", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "#",
        description: "Build features for the Meesho app and website. We look for developers who can ship fast and maintain quality."
    },
    {
        id: "job-47",
        title: "Software Tester",
        company: "HCL Tech",
        location: "Noida, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "SQL", "Basics of Java", "SDLC"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "#",
        description: "HCL is hiring freshers for software testing roles. Understanding of testing life cycle and defect management is preferred."
    },
    {
        id: "job-48",
        title: "Content Writer",
        company: "YourStory",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["Writing", "Editing", "SEO", "Journalism"],
        source: "Internshala",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "#",
        description: "Write inspiring stories about startups and entrepreneurs. Excellent command over English is a must."
    },
    {
        id: "job-49",
        title: "Java Full Stack Developer",
        company: "Cognizant",
        location: "Chennai, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["Java", "Spring Boot", "Angular", "SQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "#",
        description: "Full stack development with Java backend and Angular frontend. Experience in agile delivery is preferred."
    },
    {
        id: "job-50",
        title: "Product Manager",
        company: "Paytm",
        location: "Noida, India",
        mode: "Onsite",
        experience: "3-5 Years",
        skills: ["Product Management", "Analytics", "UX", "Strategy"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "20–35 LPA",
        applyUrl: "#",
        description: "Lead product initiatives at Paytm. You will define the roadmap and work with engineering to deliver value to users."
    },
    // 51-60
    {
        id: "job-51",
        title: "AI Researcher",
        company: "Google Research",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Machine Learning", "Python", "Research", "Math"],
        source: "Company Career Page",
        postedDaysAgo: 5,
        salaryRange: "30–50 LPA",
        applyUrl: "#",
        description: "Conduct cutting-edge research in AI. PhD or strong Master's with publication record preferred."
    },
    {
        id: "job-52",
        title: "System Administrator",
        company: "Wipro",
        location: "Chennai, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: ["Windows Server", "VMware", "Active Directory", "Networking"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "4–7 LPA",
        applyUrl: "#",
        description: "Manage Windows server infrastructure. Knowledge of virtualization and backup is required."
    },
    {
        id: "job-53",
        title: "Digital Marketing Executive",
        company: "Nykaa",
        location: "Mumbai, India",
        mode: "Hybrid",
        experience: "0-1 Years",
        skills: ["SEO", "SEM", "Social Media", "Analytics"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "5–8 LPA",
        applyUrl: "#",
        description: "Execute digital marketing strategies for Nykaa. Experience with Google Ads and Facebook Ads is a plus."
    },
    {
        id: "job-54",
        title: "Frontend Engineer",
        company: "ShareChat",
        location: "Bangalore, India",
        mode: "Remote",
        experience: "1-3 Years",
        skills: ["React", "Redux", "Performance", "Mobile Web"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "18–28 LPA",
        applyUrl: "#",
        description: "Build fast and engaging web experiences for ShareChat users. Focus on performance and cross-browser compatibility."
    },
    {
        id: "job-55",
        title: "ASP.NET Developer",
        company: "L&T Infotech",
        location: "Mumbai, India",
        mode: "Onsite",
        experience: "1-3 Years",
        skills: [".NET Core", "C#", "SQL Server", "MVC"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5–9 LPA",
        applyUrl: "#",
        description: "Back end development using Microsoft technologies. Strong OOP concepts required."
    },
    {
        id: "job-56",
        title: "Data Scientist",
        company: "Walmart Global Tech",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["Python", "Machine Learning", "SQL", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–25 LPA",
        applyUrl: "#",
        description: "Analyze retail data to optimize supply chain and customer experience. Strong statistical modeling skills needed."
    },
    {
        id: "job-57",
        title: "Manual Tester",
        company: "Tech Mahindra",
        location: "Pune, India",
        mode: "Onsite",
        experience: "0-1 Years",
        skills: ["Manual Testing", "Jira", "Test Cases", "Regression"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3–4.5 LPA",
        applyUrl: "#",
        description: "Execute test cases and report defects. Tech Mahindra is looking for detail-oriented software testers."
    },
    {
        id: "job-58",
        title: "Intern - Supply Chain",
        company: "Amazon",
        location: "Hyderabad, India",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Excel", "Analytics", "Operations", "Logistics"],
        source: "Company Career Page",
        postedDaysAgo: 2,
        salaryRange: "₹30k/month",
        applyUrl: "#",
        description: "Learn supply chain operations at Amazon. Good analytical and problem-solving skills are required."
    },
    {
        id: "job-59",
        title: "PHP Developer",
        company: "Naukri.com",
        location: "Noida, India",
        mode: "Hybrid",
        experience: "1-3 Years",
        skills: ["PHP", "Laravel", "MySQL", "JavaScript"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "#",
        description: "Develop web applications using PHP frameworks. Experience with high-traffic websites is a plus."
    },
    {
        id: "job-60",
        title: "Security Engineer",
        company: "Flipkart",
        location: "Bangalore, India",
        mode: "Hybrid",
        experience: "3-5 Years",
        skills: ["App Security", "Penetration Testing", "Cloud Security", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        applyUrl: "#",
        description: "Secure Flipkart's platform and infrastructure. Expertise in application security and devsecops is required."
    }
];
